# Generated by Django 5.2.12 on 2026-09-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('branch_year', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('social_link', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
    ]
