# Generated by Django 6.1.1 on 2026-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='anime_character',
            field=models.CharField(blank=True, help_text='Companion Anime Character (e.g., Luffy, Gojo, Zoro, Naruto)', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='anime_quote',
            field=models.CharField(blank=True, help_text='Famous anime dialogue or quote', max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bounty_or_power',
            field=models.CharField(blank=True, help_text='e.g., Power Level: 9000+ or Bounty: ฿1,500,000,000', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='special_power',
            field=models.CharField(blank=True, help_text='e.g., Domain Expansion: Infinite Logic', max_length=150),
        ),
    ]
