# Generated by Django 6.1.1 on 2026-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember_anime_character_teammember_anime_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.TextField(blank=True, help_text='Direct image URL or persistent auto-generated Data URI'),
        ),
    ]
