# Generated by Django 5.2.12 on 2026-09-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'COMPS'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('MECH', 'MECH')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2),
        ),
    ]
