# Generated by Django 5.2.12 on 2026-09-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
    ]
