# Generated by Django 6.1.1 on 2026-09-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ('-points', '-best_streak', '-current_streak', 'cached_rank', 'user__username')},
        ),
    ]
