# Generated by Django 6.1.1 on 2026-09-27 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['-points', '-best_streak', '-current_streak', 'cached_rank'], name='accounts_st_points_55d164_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['branch', '-points'], name='accounts_st_branch_af3841_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['cached_rank'], name='accounts_st_cached__6cee3d_idx'),
        ),
    ]
