# Generated by Django 5.2.12 on 2026-09-03 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('puzzles_participated', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-points', '-best_streak', '-correct_answers', 'user__username'),
                'indexes': [models.Index(fields=['year', 'month', '-points'], name='leaderboard_year_54f9d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_monthly_score')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('puzzles_participated', models.PositiveIntegerField()),
                ('best_streak', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month'),
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_monthly_winner')],
            },
        ),
    ]
