# Generated by Django 5.2.12 on 2026-09-03 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('solution', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(editable=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzle_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_value', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('submitted_at',),
            },
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['start_time', 'end_time', 'is_processed'], name='puzzles_puz_start_t_ae6341_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['puzzle', 'is_correct', 'submitted_at'], name='puzzles_sub_puzzle__eccb4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'puzzle'), name='unique_submission_per_puzzle'),
        ),
    ]
