# Generated by Django 5.2.12 on 2026-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
